# Generated by Django 3.1.5 on 2021-01-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Drug',
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs_prescribed', to='receipt_home.drug'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_given', to='receipt_home.treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
