# Generated by Django 3.1.5 on 2021-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0002_auto_20210118_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
