# Generated by Django 3.1.5 on 2021-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0005_auto_20210118_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='ammount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
