# Generated by Django 3.1.5 on 2021-02-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0007_auto_20210118_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='ammount',
            new_name='amount',
        ),
    ]
