# Generated by Django 3.1.5 on 2021-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0008_auto_20210201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='desc',
            field=models.CharField(default='', max_length=30),
        ),
    ]
