# Generated by Django 3.1.5 on 2021-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0009_auto_20210206_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='code_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
