# Generated by Django 3.1.5 on 2021-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0010_drug_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drug_test',
            field=models.CharField(default='Drug', max_length=10),
        ),
    ]
