# Generated by Django 3.1.5 on 2021-02-11 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt_home', '0012_auto_20210207_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=2)),
                ('product', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_office', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
