# Generated by Django 3.1.5 on 2021-02-12 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_home', '0013_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 12, 15, 34, 474427, tzinfo=utc)),
        ),
    ]
